DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS sleep_schedule;
DROP TABLE IF EXISTS image;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE sleep_schedule (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  days TINYTEXT NOT NULL,
  time TINYTEXT NOT NULL
);

CREATE TABLE image (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  name TEXT NOT NULL,
  hash TEXT NOT NULL,
  size INTEGER NOT NULL,
  mode INTEGER NOT NULL DEFAULT 22,
  color INTEGER NOT NULL DEFAULT 2,
  shadow INTEGER NOT NULL DEFAULT 1
);