import os
import tempfile

"""
SLEEP STATUS
"""
SLEEP_STATUS_AWAKE = 0
SLEEP_STATUS_SLEEP = 1


"""
TIME MODE
"""
TIMEMODE_OFF = 0
TIMEMODE_SECT_9_TOP_LEFT = 1
TIMEMODE_SECT_9_TOP_CENTER = 2
TIMEMODE_SECT_9_TOP_RIGHT = 3
TIMEMODE_SECT_9_MIDDLE_LEFT = 4
TIMEMODE_SECT_9_MIDDLE_CENTER = 5
TIMEMODE_SECT_9_MIDDLE_RIGHT = 6
TIMEMODE_SECT_9_BOTTOM_LEFT = 7
TIMEMODE_SECT_9_BOTTOM_CENTER = 8
TIMEMODE_SECT_9_BOTTOM_RIGHT = 9
TIMEMODE_SECT_6_TOP_LEFT = 10
TIMEMODE_SECT_6_TOP_RIGHT = 11
TIMEMODE_SECT_6_MIDDLE_LEFT = 12
TIMEMODE_SECT_6_MIDDLE_RIGHT = 13
TIMEMODE_SECT_6_BOTTOM_LEFT = 14
TIMEMODE_SECT_6_BOTTOM_RIGHT = 15
TIMEMODE_SECT_4_TOP_LEFT = 16
TIMEMODE_SECT_4_TOP_RIGHT = 17
TIMEMODE_SECT_4_BOTTOM_LEFT = 18
TIMEMODE_SECT_4_BOTTOM_RIGHT = 19
TIMEMODE_FULL_1 = 20  # Small
TIMEMODE_FULL_2 = 21  # Medium
TIMEMODE_FULL_3 = 22  # Large


"""
REDIS CONSTS
"""
R_CH_SUB_CLOCKPI: str = "clockpi"
R_CH_SUB_CALLER_EPDPI: str = "caller_epdpi"
R_CH_SUB_CALLER_WP_ESP32_1: str = "caller_wp_esp32_1"

R_CH_PUB_EPDPI: str = "epdpi"
R_CH_PUB_WP_ESP32_1: str = "wp_esp32_1"

R_MSG_CLEAR: str = "clear"
R_MSG_DRAW: str = "draw"
R_MSG_BUSY: str = "busy"
R_MSG_UPDATED: str = "updated"
R_MSG_RESULT: str = "result"

R_IMAGE_QUEUE: str = "img_queue"
R_SLEEP_STATUS: str = "sleep_status"

R_SETTINGS_EPD_BUSY: str = "epd_busy"
R_SETTINGS_DRAW_GRIDS: str = "draw_grids"


"""
ERROR CODES
"""
# Exceptions - Auth (100)

# Exceptions - EPD (200)

# Exceptions - Main (300)

# Exceptions - Queue (400)
ERR_QUEUE_INVALID_ID = -401
ERR_QUEUE_TOO_SHORT = -402
ERR_QUEUE_DUPLICATE_ID = -403

# Exceptions Sleep (500)
ERR_SLEEP_INVALID_DATA = -501
ERR_SLEEP_INVALID_ID = -502

# Exceptions - Wallpaper (600)
ERR_UPLOAD_NO_FILE = -601
ERR_UPLOAD_INVALID_EXT = -602
ERR_UPLOAD_INVALID_IMAGE = -603
ERR_UPLOAD_POST_PROC = -604
ERR_UPLOAD_HASH = -605
ERR_UPLOAD_COPY = -606
ERR_UPLOAD_SAVE = -607
ERR_WALLPAPER_INVALID_DATA = -608
ERR_WALLPAPER_INVALID_ID = -609


"""
DIRECTORIES
"""
DIR_APP_UPLOAD: str = os.path.join(os.path.dirname(__file__), "..", "upload")
DIR_FONT: str = os.path.join(os.path.dirname(__file__), "..", "font")
DIR_TMP_UPLOAD: str = os.path.join(tempfile.gettempdir(), "upload")
DIR_TMP_PROCESSED: str = os.path.join(tempfile.gettempdir(), "processed")
