"""empty message

Revision ID: 80fbadd307cc
Revises: 345700da477e
Create Date: 2025-07-18 17:22:25.017399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80fbadd307cc'
down_revision = '345700da477e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(), server_default='User', nullable=False))

    with op.batch_alter_table('sleep_schedule', schema=None) as batch_op:
        batch_op.alter_column('enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sleep_schedule', schema=None) as batch_op:
        batch_op.alter_column('enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
