"""add new row 'is_show_time' to device table

Revision ID: b1a345671741
Revises: 8a4b1f75e996
Create Date: 2025-12-05 21:50:31.096118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1a345671741'
down_revision = '8a4b1f75e996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_show_time', sa.Boolean(), server_default='t', nullable=False))

    with op.batch_alter_table('wallpaper', schema=None) as batch_op:
        batch_op.alter_column('label_x_per',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=1),
               existing_nullable=False)
        batch_op.alter_column('label_y_per',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=1),
               existing_nullable=False)
        batch_op.alter_column('label_w_per',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=1),
               existing_nullable=False)
        batch_op.alter_column('label_h_per',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=1),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallpaper', schema=None) as batch_op:
        batch_op.alter_column('label_h_per',
               existing_type=sa.Float(precision=1),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('label_w_per',
               existing_type=sa.Float(precision=1),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('label_y_per',
               existing_type=sa.Float(precision=1),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('label_x_per',
               existing_type=sa.Float(precision=1),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('is_show_time')

    # ### end Alembic commands ###
