"""empty message

Revision ID: e3a2565910f6
Revises: 79bc05b243b8
Create Date: 2025-08-23 21:48:38.235801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3a2565910f6'
down_revision = '79bc05b243b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallpaper', schema=None) as batch_op:
        batch_op.alter_column('w',
               existing_type=sa.INTEGER(),
               type_=sa.Float(precision=1),
               existing_nullable=False)
        batch_op.alter_column('h',
               existing_type=sa.INTEGER(),
               type_=sa.Float(precision=1),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallpaper', schema=None) as batch_op:
        batch_op.alter_column('h',
               existing_type=sa.Float(precision=1),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('w',
               existing_type=sa.Float(precision=1),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
